services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: intranet
      POSTGRES_PASSWORD: intranet_pass
      POSTGRES_DB: intranet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
