name: Force Stock Images

on:
  workflow_dispatch:
    inputs:
      filter:
        description: "Substring to filter posts by slug/title (optional)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Replace blog images with stock per category
        env:
          PLACEHOLDERS_PREFER_NODE: '1'
          PLACEHOLDERS_FORCE: '1'
        run: |
          if [ -n "${{ github.event.inputs.filter }}" ]; then
            echo "Filter: ${{ github.event.inputs.filter }}"
            node scripts/generate_missing_images_runner.js --node --force --filter "${{ github.event.inputs.filter }}"
          else
            node scripts/generate_missing_images_runner.js --node --force
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(images): replace blog images with stock category photos"
          title: "chore(images): replace blog images with stock"
          body: |
            This PR replaces blog hero images with stock category photos using the Node runner.
          branch: "images/stock-replace-${{ github.run_id }}"
          delete-branch: true
          add-paths: |
            public/images/blog/**
