name: Intranet E2E

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run intranet E2E (in-memory)
        env:
          CI: '1'
          USE_IN_MEMORY_DB: '1'
          SKIP_CONTENTLAYER: '1'
        run: pnpm intranet:e2e:memory
