name: Intranet E2E

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Enable corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.12.3 --activate
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run intranet E2E (in-memory)
        env:
          CI: '1'
          USE_IN_MEMORY_DB: '1'
          SKIP_CONTENTLAYER: '1'
        run: pnpm intranet:e2e:memory
