name: Manual Vercel Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deploy environment (preview|production)"
        required: true
        default: "production"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Verify Vercel CLI
        run: |
          npx vercel --version
          npx vercel whoami --token=$VERCEL_TOKEN

      - name: Pull Vercel environment
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          else
            npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          fi
        timeout-minutes: 10

      - name: Build
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            npx vercel build --prod --token=$VERCEL_TOKEN
          else
            npx vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy
        run: |
          if [ "${{ github.event.inputs.environment }}" = "production" ]; then
            npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            npx vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi

