name: Security Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  node-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Instalar dependencias
        run: pnpm install
      - name: Auditoría de seguridad Node.js
        run: pnpm audit --audit-level=moderate

  python-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run: pip install --upgrade -r tools/requirements.txt
      - name: Auditoría de seguridad Python
        run: pip install pip-audit && pip-audit
