name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

concurrency:
  group: pr-${{ github.event.pull_request.number }}-preview
  cancel-in-progress: true

jobs:
  preview-deploy:
    name: Deploy Preview to Vercel
    runs-on: ubuntu-latest
    # Evita forks (sin secretos comprobados en tiempo de ejecución)
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Vercel secrets
        id: check_secrets
        run: |
          # Expose secrets to this step via GITHUB_ENV so the linter doesn't flag them in YAML
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV

          missing=0
          if [ -z "$VERCEL_TOKEN" ]; then echo "VERCEL_TOKEN missing"; missing=1; fi
          if [ -z "$VERCEL_ORG_ID" ]; then echo "VERCEL_ORG_ID missing"; missing=1; fi
          if [ -z "$VERCEL_PROJECT_ID" ]; then echo "VERCEL_PROJECT_ID missing"; missing=1; fi
          if [ $missing -eq 1 ]; then echo "skip=true" >> $GITHUB_OUTPUT; else echo "skip=false" >> $GITHUB_OUTPUT; fi
        shell: bash

      # Despliega un Preview en Vercel para este commit. Si se provee github-token,
      # la acción comenta automáticamente la URL del preview en el PR.
      - name: Vercel Preview Deploy (CLI)
        id: vercel_cli
        if: ${{ steps.check_secrets.outputs.skip == 'false' }}
        run: |
          # Secrets were written to GITHUB_ENV in the previous step and are available here
          corepack enable
          corepack prepare pnpm@9.12.3 --activate
          # Deployment de preview (sin --prod). --yes evita prompts.
          # Capturamos la URL desde la salida de la CLI.
          url=$(pnpm dlx vercel --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" --confirm | sed -n 's/.*https:\/\/\(.*\.vercel\.app\).*/https:\/\/\1/p' | tail -n1)
          echo "Preview URL: $url"
          if [ -n "$url" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Comment URL on PR
        if: ${{ github.event_name == 'pull_request' && steps.vercel_cli.outputs.url != '' && steps.check_secrets.outputs.skip == 'false' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = process.env.PREVIEW_URL;
            if (!url) return;
            const body = `Preview desplegado: ${url}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            })
        env:
          PREVIEW_URL: ${{ steps.vercel_cli.outputs.url }}

      - name: Skipped reason
        if: ${{ steps.check_secrets.outputs.skip == 'true' }}
        run: |
          echo "Skipping preview deploy. Missing Vercel secrets or configuration."
        shell: bash
