name: PR Preview Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

# concurrency:
#   group: pr-${{ github.event.pull_request.number }}-preview
#   cancel-in-progress: true

jobs:
  preview-deploy:
    name: Deploy Preview to Vercel
    runs-on: self-hosted
    # Evita forks (sin secretos comprobados en tiempo de ejecución)
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check Vercel secrets
        id: check_secrets
        run: |
          # Check if secrets exist and expose them to GITHUB_ENV
          if [ -n "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
            echo "VERCEL_TOKEN present"
          else
            echo "VERCEL_TOKEN missing"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ -n "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV
            echo "VERCEL_PROJECT_ID present"
          else
            echo "VERCEL_PROJECT_ID missing"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "skip=false" >> $GITHUB_OUTPUT
        shell: bash

      # Despliega un Preview en Vercel para este commit. Si se provee github-token,
      # la acción comenta automáticamente la URL del preview en el PR.
      - name: Vercel Preview Deploy (CLI)
        id: vercel_cli
        if: ${{ steps.check_secrets.outputs.skip == 'false' }}
        run: |
          # Secrets were written to GITHUB_ENV in the previous step and are available here
          echo "Starting Vercel deployment..."
          echo "VERCEL_TOKEN is set: $(if [ -n "$VERCEL_TOKEN" ]; then echo "yes"; else echo "no"; fi)"
          echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
          
          corepack enable
          corepack prepare pnpm@9.12.3 --activate
          
          # First, try to link the project if not already linked
          echo "Checking if project is linked..."
          if [ ! -f ".vercel/project.json" ]; then
            echo "Project not linked, linking..."
            pnpm dlx vercel link --yes --token "$VERCEL_TOKEN" --project "$VERCEL_PROJECT_ID" || echo "Link failed, continuing..."
          fi
          
          # Deployment de preview (sin --prod). --yes evita prompts.
          # Capturamos la URL desde la salida de la CLI.
          echo "Starting preview deployment..."
          timeout 300 pnpm dlx vercel --yes --token "$VERCEL_TOKEN" 2>&1 | tee vercel_output.log
          
          # Extract URL from output
          url=$(grep -o 'https://[^[:space:]]*\.vercel\.app' vercel_output.log | tail -n1)
          echo "Extracted Preview URL: $url"
          
          if [ -n "$url" ]; then
            echo "url=$url" >> $GITHUB_OUTPUT
          else
            echo "No URL found in output"
            cat vercel_output.log
          fi
        shell: bash

      - name: Comment URL on PR
        if: ${{ github.event_name == 'pull_request' && steps.vercel_cli.outputs.url != '' && steps.check_secrets.outputs.skip == 'false' }}
        uses: actions/github-script@v7
        with:
          script: |
            const url = process.env.PREVIEW_URL;
            if (!url) return;
            const body = `Preview desplegado: ${url}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            })
        env:
          PREVIEW_URL: ${{ steps.vercel_cli.outputs.url }}

      - name: Skipped reason
        if: ${{ steps.check_secrets.outputs.skip == 'true' }}
        run: |
          echo "Skipping preview deploy. Missing Vercel secrets or configuration."
        shell: bash
